Přidání loga JmK (a SI) k patřičným epizodám
faktaoklimatu/web-2050podcast pull request #90
Opened 2023-01-27 16:33 UTC by jankrcal

2023-01-27 16:58 UTC, jankrcal commented
@katkolouchova Můžeš prosím zhodnotit svým cvičeným okem, jestli je to vizuálně ok?
(je to kvůli grantům, stačí merge v pondělí)

2023-01-29 23:34 UTC, mukrop commented
Drobnost: Episoda vznikla s podporou Jihomoravskeho kraja, nie v spolupraci s Krajskym uradom JMK. Prosim upravte aj ten wording. Navrhujem wording "Vznik této epizody finančně podpořil", ktory ma E26 (lebo napriklad E22 ma nieco ine),

Inak vizualy mi pridu OK (dalo by sa to tam zakomponovat asi aj nejako lepsie, ale good enough).

[Pravidla pro publicitu JMK](https://dotace.kr-jihomoravsky.cz/Uploads/6710-7-Pravidla+pro+publicitu+JMKpdf.aspx)

2023-01-30 07:40 UTC, jankrcal commented
Díky za připomínku, upraveno.

2023-01-30 07:41 UTC, jankrcal commented
Ještě jako FYI @letajicitreska, abys viděl, co ti tady upravujeme :)

2023-01-30 10:36 UTC, katkolouchova requested changes
@jankrcal Vizuálně za mě ok :) Akorát se loga nezobrazují ve Firefoxu. V Chrome ano. Mrkni na to ještě prosím.

2023-01-30 11:45 UTC, katkolouchova approved these changes

2023-01-30 11:46 UTC, merged